name: "Build legacy Nix package on Ubuntu"

on:
  push:

# TODO: Add a job for tests
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache install Nix packages
        uses: rikhuijzer/cache-install@v1
        with:
          key: ${{ runner.os }}-nix-${{ hashFiles('./flake.lock', './flake.nix') }}
      
      - name: Building package
        run: nix --experimental-features 'nix-command flakes' build
